version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.22
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-174-129-41-12.compute-1.amazonaws.com
            database: d6hkco659ra8i3
            ssl: true
            user: zaefpfkhnawnja
            password: 6bb263198e98beba98eed74cc58bb6f3ba151e478c7727fd772d1240ed86cb7c
            rawAccess: true
            port: '5432'
            migrations: true